In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [76]:
df = pd.read_excel("pokemon_data.xlsx")

In [4]:
df[0:10]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weakness,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"Grass, Poison",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"Fire, Ice, Flying, Psychic","Ivysaur, Venusaur",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"Grass, Poison",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","Fire, Ice, Flying, Psychic",Venusaur,Bulbasaur
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"Grass, Poison",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"Fire, Ice, Flying, Psychic",NaN,"Bulbasaur, Ivysaur"
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,Fire,0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"Water, Ground, Rock","Charmeleon, Charizard",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,Fire,1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"Water, Ground, Rock",Charizard,Charmander
5,6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"Fire, Flying",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"Water, Electric, Rock",NaN,"Charmander, Charmeleon"
6,7,7,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,Water,0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"Electric, Grass","Wartortle, Blastoise",NaN
7,8,8,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,Water,0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"Electric, Grass",Blastoise,Squirtle
8,9,9,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,Water,1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,NaN,"Electric, Grass",NaN,"Squirtle, Wartortle"
9,10,10,Caterpie,http://www.serebii.net/pokemongo/pokemon/010.png,Bug,0.30 m,2.9 kg,Caterpie Candy,12.0,2 km,3.0320,303.20,16:35,[1.05],"Fire, Flying, Rock","Metapod, Butterfree",NaN

# ● Get all Pokemons whose spawn rate is less than 5%

In [31]:
df1 = df[df['spawn_chance']<5]

In [32]:
df1 = df1[['name','spawn_chance']]

In [34]:
print(f"""all Pokemons whose spawn rate is less than 5% are\n\n{df1}""")

all Pokemons whose spawn rate is less than 5% are

           name  spawn_chance
0     Bulbasaur        0.6900
1       Ivysaur        0.0420
2      Venusaur        0.0170
3    Charmander        0.2530
4    Charmeleon        0.0120
..          ...           ...
146     Dratini        0.3000
147   Dragonair        0.0200
148   Dragonite        0.0011
149      Mewtwo        0.0000
150         Mew        0.0000

[128 rows x 2 columns]

# ● Get all Pokemons that have less than 4 weaknesses

In [37]:
df2 = df[df['weakness'].str.count(',')<3]

In [38]:
df2 = df2[['name', 'weakness']]

In [39]:
print(f"""all Pokemons that have less than 4 weaknesses are\n\n{df2}""")

all Pokemons that have less than 4 weaknesses are

           name               weakness
3    Charmander    Water, Ground, Rock
4    Charmeleon    Water, Ground, Rock
5     Charizard  Water, Electric, Rock
6      Squirtle        Electric, Grass
7     Wartortle        Electric, Grass
..          ...                    ...
145     Moltres  Water, Electric, Rock
146     Dratini     Ice, Dragon, Fairy
147   Dragonair     Ice, Dragon, Fairy
149      Mewtwo       Bug, Ghost, Dark
150         Mew       Bug, Ghost, Dark

[102 rows x 2 columns]

# Get all Pokemons that have no multipliers at all

In [51]:
df3 = df[df['multipliers'].isnull()]

In [52]:
df3 = df3[['name', 'multipliers']]

In [53]:
print(f"""all Pokemons that have no multipliers at all are\n\n{df3}""")

all Pokemons that have no multipliers at all are

          name multipliers
2     Venusaur         NaN
5    Charizard         NaN
8    Blastoise         NaN
14    Beedrill         NaN
17     Pidgeot         NaN
..         ...         ...
144     Zapdos         NaN
145    Moltres         NaN
148  Dragonite         NaN
149     Mewtwo         NaN
150        Mew         NaN

[68 rows x 2 columns]

# Get all Pokemons that do not have more than 2 evolutions

In [60]:
df4 = df[df['next_evolution'].str.count(',')<2]

In [61]:
df4['evolution_count'] = df['next_evolution'].str.count(',')

C:\Users\8092\AppData\Local\Temp\ipykernel_18348\697381262.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['evolution_count'] = df['next_evolution'].str.count(',')

In [62]:
df4 = df4[['name', 'evolution_count', 'next_evolution' ]]

In [63]:
print(f"""all Pokemons that do not have more than 2 evolutions are\n\n{df4}""")

all Pokemons that do not have more than 2 evolutions are

           name  evolution_count         next_evolution
0     Bulbasaur              1.0      Ivysaur, Venusaur
1       Ivysaur              0.0               Venusaur
3    Charmander              1.0  Charmeleon, Charizard
4    Charmeleon              0.0              Charizard
6      Squirtle              1.0   Wartortle, Blastoise
..          ...              ...                    ...
128    Magikarp              0.0               Gyarados
137     Omanyte              0.0                Omastar
139      Kabuto              0.0               Kabutops
146     Dratini              1.0   Dragonair, Dragonite
147   Dragonair              0.0              Dragonite

[63 rows x 3 columns]

# Get all Pokemons whose spawn time is less than 300 seconds.

In [78]:
df['spawn_time'] = df['spawn_time'].astype('str')
df['spawn_time'] = (df['spawn_time'].apply(lambda x: '00:'+x))
df

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weakness,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"Grass, Poison",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,00:20:00,[1.58],"Fire, Ice, Flying, Psychic","Ivysaur, Venusaur",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"Grass, Poison",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,00:07:00,"[1.2, 1.6]","Fire, Ice, Flying, Psychic",Venusaur,Bulbasaur
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"Grass, Poison",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,00:11:30,NaN,"Fire, Ice, Flying, Psychic",NaN,"Bulbasaur, Ivysaur"
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,Fire,0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,00:08:45,[1.65],"Water, Ground, Rock","Charmeleon, Charizard",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,Fire,1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,00:19:00,[1.79],"Water, Ground, Rock",Charizard,Charmander
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,Dragon,1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,00:06:41,"[1.83, 1.84]","Ice, Dragon, Fairy","Dragonair, Dragonite",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,Dragon,3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,00:11:57,[2.05],"Ice, Dragon, Fairy",Dragonite,Dratini
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"Dragon, Flying",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,00:23:38,NaN,"Ice, Rock, Dragon, Fairy",NaN,"Dratini, Dragonair"
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,Psychic,2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,00:nan,NaN,"Bug, Ghost, Dark",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,Psychic,0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,00:nan,NaN,"Bug, Ghost, Dark",NaN,NaN

In [79]:
pd.to_timedelta(df['spawn_time'])

ValueError: expected hh:mm:ss format

# Get all Pokemon who have more than two types of capabilities

In [88]:
df5 = df[df['type'].str.count(',')>2]

In [89]:
df5['capabilities_count'] = df5['next_evolution'].str.count(',')

In [90]:
df5 = df5[['name', 'capabilities_count', 'type']]

In [91]:
print(f"""all Pokemon who have more than two types of capabilities are\n\n{df5}""")

all Pokemon who have more than two types of capabilities are

Empty DataFrame
Columns: [name, capabilities_count, type]
Index: []